spring:

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/echobrief}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: 7a8f3c2e1b9d4f6a0e5c8b2d7f1a3e9c4b6d0f2a8e5c1b7d3f9a4e6c0b2d8f1a
  expiration: 86400000

groq:
  api-key: ${GROQ_API_KEY}

elevenlabs:
  api-key: ${ELEVENLABS_API_KEY}
  voice-id: DZ5dz5D8nJ5V11UhEelX
